# Generated by Django 3.1.2 on 2020-10-17 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201017_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
    ]
